name: Release Plugin

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add Version as environment variable
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
    
      - name: Add version to manifest file
        run: |
          # Change $VERSION in the manifest.yml to the version of the release
          envsubst < manifest.template.yml > manifest_temp.yml && mv manifest_temp.yml manifest.yml

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build
        run: |
          TARGETS=(
            "x86_64-unknown-linux-gnu|${{ github.event.repository.name }}_${{ github.ref_name }}_linux_amd64"
            "aarch64-unknown-linux-gnu||${{ github.event.repository.name }}_${{ github.ref_name }}_linux_arm64"
            "x86_64-apple-darwin|${{ github.event.repository.name }}_${{ github.ref_name }}_darwin_amd64"
            "aarch64-apple-darwin|${{ github.event.repository.name }}_${{ github.ref_name }}_darwin_arm64"
            "x86_64-pc-windows-msvc|${{ github.event.repository.name }}_${{ github.ref_name }}_windows_amd64"
          )  
          mkdir -p "dist"
          for entry in "${TARGETS[@]}"; do
            target=${entry%%|*}
            artifact_name=${entry#*|}
            mkdir -p "target/$artifact_name"
            deno compile --allow-run --allow-env --allow-read --allow-sys --allow-net --target "$target" -o "target/$artifact_name/binary" main.ts
            cp manifest.yml "target/$artifact_name/manifest.yml"
            tar -czf "dist/$artifact_name.tar.gz" -C "target/$artifact_name" .
          done
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifacts-${{ github.ref_name }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: plugin-artifacts-${{ github.ref_name }}
          path: dist/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}